### ISSUE TITLE
[SUGGESTION] Trick to select other bullet slot in CAD

### ISSUE THREAD

**Issue by Xechon** [Kamefrede/psitestaddon#9]
This would allow for using different bullets as functions so that spells can be linked or data can be stored by one spell and used by another without manual switching. Related, a way to read the currently selected slot may be useful, and both slot reading and selection could be added for the player's hotbar as well.

**Comment by Kamefrede** [comment]
Hi!
I heard from some reliable sources that the *next* PSI update is going to include something of the likes, so I don't think I should really be doing this. If Vazkii does not end up adding this I'll consider it.
For now closed
